import polars as pl

MASTER_RAW_COLUMNS: tuple[str, ...] = (
    "Symbol",
    "Security_Description",
    "CUSIP",
    "Security_Type",
    "SIP_Symbol",
    "Old_Symbol",
    "Test_Symbol_Flag",
    "Listed_Exchange",
    "Tape",
    "Unit_Of_Trade",
    "Round_Lot",
    "NYSE_Industry_Code",
    "Shares_Outstanding",
    "Halt_Delay_Reason",
    "Specialist_Clearing_Agent",
    "Specialist_Clearing_Number",
    "Specialist_Post_Number",
    "Specialist_Panel",
    "TradedOnNYSEMKT",
    "TradedOnNASDAQBX",
    "TradedOnNSX",
    "TradedOnFINRA",
    "TradedOnISE",
    "TradedOnEdgeA",
    "TradedOnEdgeX",
    "TradedOnNYSETexas",
    "TradedOnNYSE",
    "TradedOnArca",
    "TradedOnNasdaq",
    "TradedOnCBOE",
    "TradedOnPSX",
    "TradedOnBATSY",
    "TradedOnBATS",
    "TradedOnIEX",
    "Tick_Pilot_Indicator",
    "Effective_Date",
    "TradedOnLTSE",
    "TradedOnMEMX",
    "TradedOnMIAX",
    "TradedOn24X",
)

TRADE_RAW_COLUMNS: tuple[str, ...] = (
    "Time",
    "Exchange",
    "Symbol",
    "Sale Condition",
    "Trade Volume",
    "Trade Price",
    "Trade Stop Stock Indicator",
    "Trade Correction Indicator",
    "Sequence Number",
    "Trade Id",
    "Source of Trade",
    "Trade Reporting Facility",
    "Participant Timestamp",
    "Trade Reporting Facility TRF Timestamp",
    "Trade Through Exempt Indicator",
)

QUOTE_RAW_COLUMNS: tuple[str, ...] = (
    "Time",
    "Exchange",
    "Symbol",
    "Bid_Price",
    "Bid_Size",
    "Offer_Price",
    "Offer_Size",
    "Quote_Condition",
    "Sequence_Number",
    "National_BBO_Ind",
    "FINRA_BBO_Indicator",
    "FINRA_ADF_MPID_Indicator",
    "Quote_Cancel_Correction",
    "Source_Of_Quote",
    "Retail_Interest_Indicator",
    "Short_Sale_Restriction_Indicator",
    "LULD_BBO_Indicator",
    "SIP_Generated_Message_Identifier",
    "National_BBO_LULD_Indicator",
    "Participant_Timestamp",
    "FINRA_ADF_Timestamp",
    "FINRA_ADF_Market_Participant_Quote_Indicator",
    "Security_Status_Indicator",
)

TRADE_SCHEMA_OVERRIDES: dict[str, pl.DataType] = {
    "Time": pl.Int64,
    "Exchange": pl.String,
    "Symbol": pl.String,
    "Sale Condition": pl.String,
    "Trade Volume": pl.Int64,
    "Trade Price": pl.Float64,
    "Trade Stop Stock Indicator": pl.String,
    "Trade Correction Indicator": pl.Int64,
    "Sequence Number": pl.Int64,
    "Trade Id": pl.Int64,
    "Source of Trade": pl.String,
    "Trade Reporting Facility": pl.String,
    "Participant Timestamp": pl.Int64,
    "Trade Reporting Facility TRF Timestamp": pl.String,
    "Trade Through Exempt Indicator": pl.Int64,
}

QUOTE_SCHEMA_OVERRIDES: dict[str, pl.DataType] = {
    "Time": pl.Int64,
    "Exchange": pl.String,
    "Symbol": pl.String,
    "Bid_Price": pl.Float64,
    "Bid_Size": pl.Int64,
    "Offer_Price": pl.Float64,
    "Offer_Size": pl.Int64,
    "Quote_Condition": pl.String,
    "Sequence_Number": pl.Int64,
    "National_BBO_Ind": pl.String,
    "FINRA_BBO_Indicator": pl.String,
    "FINRA_ADF_MPID_Indicator": pl.String,
    "Quote_Cancel_Correction": pl.String,
    "Source_Of_Quote": pl.String,
    "Retail_Interest_Indicator": pl.String,
    "Short_Sale_Restriction_Indicator": pl.String,
    "LULD_BBO_Indicator": pl.String,
    "SIP_Generated_Message_Identifier": pl.String,
    "National_BBO_LULD_Indicator": pl.String,
    "Participant_Timestamp": pl.Int64,
    "FINRA_ADF_Timestamp": pl.Int64,
    "FINRA_ADF_Market_Participant_Quote_Indicator": pl.String,
    "Security_Status_Indicator": pl.String,
}
